name: Changeset Bot

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  changeset-bot:
    runs-on: ubuntu-latest
    name: Changeset Bot

    steps:
      - uses: actions/checkout@v3
      - name: Run Changeset Checker
        uses: ./packages/manager/scripts/changelog
        with:
          owner: ${{ github.repository_owner }}
          repo: ${{ github.event.repository.name }}
          pr_number: ${{ github.event.number }}
          token: ${{ secrets.GITHUB_TOKEN }}
        