name: Coverage Comment

on:
  workflow_run:
    workflows: ["Code Coverage"]
    types:
      - completed

permissions:
  pull-requests: write

jobs:
  comment:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download base coverage artifact
        uses: actions/download-artifact@v3
        with:
          name: ref_code_coverage

      - name: Download current coverage artifact
        uses: actions/download-artifact@v3
        with:
          name: current_code_coverage

      - name: Update Coverage Badge
        run: yarn coverage:badge

      - name: Generate Coverage Comment
        run: |
          base_coverage=$(cat ref_code_coverage.txt)
          current_coverage=$(cat current_code_coverage.txt)
          if (( $(echo "$current_coverage < $base_coverage" | bc -l) )); then
            icon="❌" # Error icon
          else
            icon="✅" # Check mark icon
          fi
          comment_message="$icon **Coverage Report**\nBase Coverage: $base_coverage\nCurrent Coverage: $current_coverage"
          echo "Coverage: $comment_message"
          echo "$comment_message" > updated_comment.txt
      
      - name: Validate Coverage
        run: |
          base_coverage=$(cat ref_code_coverage.txt)
          current_coverage=$(cat current_code_coverage.txt)
          if (( $(echo "$current_coverage < $base_coverage" | bc -l) )); then
            echo "Error: Current coverage is lower than base coverage"
            exit 1 # Fail the check
          fi

      - name: Post Comment
        uses: mshick/add-pr-comment@7c0890544fb33b0bdd2e59467fbacb62e028a096 #v2.8.1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          message: |
            $(cat updated_comment.txt)
          
